#!/bin/sh
set -e

case "$1" in
  configure)
    touch /var/log/himpy.log
    # Ensure secure permissions (CVE-2013-0337)
    # http://bugs.debian.org/701112
    #
    # nginx uses 0755 for log files making them world readable,
    # we fix that by using 0750 for the log directory.
    #
    # Allow local admin to override:
    # e.g. dpkg-statoverride --add root adm 0755 /var/log/nginx
    useradd himpy
      chown himpy:adm /var/log/himpy.log
      chmod 0750 /var/log/himpy.log
    ;;
    

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0

